/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    media: Media;
    projects: Project;
    skills: Skill;
    experience: Experience;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    "site-settings": SiteSetting;
  };
  locale: null;
  user: User & {
    collection: "users";
  };
}

export interface UserAuthOperations {
  forgotPassword: {
    email: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
  };
}

export interface User {
  id: string;
  name?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface Media {
  id: string;
  alt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
  createdAt: string;
  updatedAt: string;
}

export interface Project {
  id: string;
  title: string;
  slug: string;
  description: string;
  longDescription?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category: "shopify" | "wordpress" | "react";
  techStack?: {
    tech: string;
    id?: string | null;
  }[] | null;
  gallery?: {
    image: string | Media;
    id?: string | null;
  }[] | null;
  demoVideo?: string | null;
  liveUrl?: string | null;
  githubUrl?: string | null;
  featured?: boolean | null;
  completedAt?: string | null;
  highlights?: {
    highlight: string;
    id?: string | null;
  }[] | null;
  createdAt: string;
  updatedAt: string;
}

export interface Skill {
  id: string;
  name: string;
  category: "frontend" | "backend" | "tools";
  proficiency: number;
  order?: number | null;
  createdAt: string;
  updatedAt: string;
}

export interface Experience {
  id: string;
  company: string;
  role: string;
  description?: string | null;
  startDate: string;
  endDate?: string | null;
  isCurrent?: boolean | null;
  highlights?: {
    highlight: string;
    id?: string | null;
  }[] | null;
  order?: number | null;
  createdAt: string;
  updatedAt: string;
}

export interface SiteSetting {
  id: string;
  siteTitle: string;
  siteDescription?: string | null;
  availableForWork?: boolean | null;
  heroGreeting?: string | null;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  heroDescription?: string | null;
  aboutTitle?: string | null;
  aboutContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  profileImage?: (string | Media) | null;
  stats?: {
    label: string;
    value: string;
    id?: string | null;
  }[] | null;
  email?: string | null;
  socialLinks?: {
    platform: "github" | "linkedin" | "twitter" | "instagram" | "youtube";
    url: string;
    id?: string | null;
  }[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}

declare module "payload" {
  export interface GeneratedTypes extends Config {}
}
